name: Refresh Shopify -> Google Sheets

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run refresh
        env:
          SHOP_DOMAIN: ${{ secrets.SHOP_DOMAIN }}
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
          API_VERSION: "2024-04"
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
          DAYS_BACK: "7"
          TAB_NAME: "Pedidos"
        run: |
          python refresh_sheet.py
